### ISSUE TITLE
使用compose部署安装出现的问题

### ISSUE THREAD

**Issue by MYJN** [lkw199711/smanga#114]
Docker版本:
>  docker-ce 5:24.0.5-1-debian.11-bullseye

Compose版本:
> docker-compose-plugin 2.20.2-1-debian.11-bullseye

smanga版本:
> 3.3.7

compose:
````
version: "3"
services:
  smanga:
    image: lkw199711/smanga:alpha
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 16M
    ports:
      - 9798:80    
      - 63306:3306 
    volumes:
      - /srv/dev-disk-by-uuid-cf6c44ac/Docker/Docker_AppData/smanga/data:/data          
      - /srv/dev-disk-by-uuid-cf6c44ac-/Docker/Docker_AppData/smanga/compress:/compress  
      - /srv/dev-disk-by-uuid-580b5dc1-/Project2/Manga:/mnt                             
    environment:
      PUID: 1000    # 想切换为哪个用户来运行程序,该用户的uid
      PGID: 1000    # 想切换为哪个用户来运行程序,该用户的gid
      UMASK: 022
      TZ: Asia/Shanghai
    restart: unless-stopped
    hostname: smanga-alpha
    container_name: smanga-alpha
````
--------------------------------------------------
* 问题一
>添加扫描之后没有出现漫画，查看数据库发现大量一下错误信息 

```
"ErrorException: dir(/mnt/日漫/XXXXX.zip): failed to open dir: Not a directory in /app/php/app/Jobs/ScanManga.php:259
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/php/app/Jobs/ScanManga.php(259): dir()
#2 /app/php/app/Jobs/ScanManga.php(144): App\Jobs\ScanManga->get_chapter_list()
#3 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\ScanManga->handle()
#4 /app/php/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#6 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /app/php/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#8 /app/php/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#9 /app/php/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /app/php/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /app/php/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#12 /app/php/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /app/php/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#14 /app/php/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /app/php/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\Pipeline\Pipeline->then()
#16 /app/php/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#17 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#18 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#19 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#20 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(329): Illuminate\Queue\Worker->runJob()
#21 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->runNextJob()
#22 /app/php/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#23 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#24 /app/php/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#25 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#26 /app/php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#27 /app/php/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#28 /app/php/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#29 /app/php/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#30 /app/php/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#31 /app/php/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#32 /app/php/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#33 /app/php/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#34 /app/php/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#35 /app/php/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#36 /app/php/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#37 {main}" 
```
--------------------------------------------------
* 问题二
> TZ已设置中国时区，数据库看到得信息时间不正确 TZ: Asia/Shanghai
```
2023-08-09 22:17:12:  路径正在扫描，放弃当前扫描任务 pathId->1

2023-08-09 22:17:15:  路径正在扫描，放弃当前扫描任务 pathId->1

2023-08-09 22:17:19:  路径正在扫描，放弃当前扫描任务 pathId->1

2023-08-10 03:07:24:  路径正在扫描，放弃当前扫描任务 pathId->1
```
